sudo : required
services:
  - docker

before_install:
  - docker build -t yousufibrahim28/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yousufibrahim28/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-591166263033"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"